import type React from "react";

export const S = {
  app: { fontFamily: "'Syne', sans-serif", minHeight: "100vh", background: "#0a0a0f", color: "#f0f0f5" } as React.CSSProperties,
  nav: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "18px 40px", borderBottom: "1px solid #1e1e2e", background: "#0a0a0f", position: "sticky", top: 0, zIndex: 100 } as React.CSSProperties,
  logo: { fontSize: 22, fontWeight: 900, letterSpacing: -1, color: "#fff" } as React.CSSProperties,
  navLinks: { display: "flex", gap: 8 } as React.CSSProperties,
  navBtn: (active: boolean): React.CSSProperties => ({ background: active ? "#f97316" : "transparent", color: active ? "#fff" : "#aaa", border: active ? "none" : "1px solid #2a2a3a", borderRadius: 10, padding: "8px 20px", cursor: "pointer", fontFamily: "inherit", fontWeight: 600, fontSize: 14, transition: "all .2s" }),
  hero: { padding: "80px 40px 60px", maxWidth: 900, margin: "0 auto", textAlign: "center" } as React.CSSProperties,
  h1: { fontSize: "clamp(2.5rem,6vw,4.5rem)", fontWeight: 900, letterSpacing: -2, lineHeight: 1.05, marginBottom: 20 } as React.CSSProperties,
  accent: { color: "#f97316" } as React.CSSProperties,
  sub: { fontSize: 18, color: "#888", maxWidth: 560, margin: "0 auto 40px", lineHeight: 1.6 } as React.CSSProperties,
  ctaBtn: { background: "#f97316", color: "#fff", border: "none", borderRadius: 14, padding: "16px 40px", fontSize: 17, fontWeight: 800, cursor: "pointer", letterSpacing: -0.3, transition: "transform .15s" } as React.CSSProperties,
  featureGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 20, padding: "0 40px 80px", maxWidth: 1100, margin: "0 auto" } as React.CSSProperties,
  featureCard: { background: "#12121c", border: "1px solid #1e1e2e", borderRadius: 18, padding: "28px 24px" } as React.CSSProperties,
  featureIcon: { fontSize: 32, marginBottom: 12 } as React.CSSProperties,
  featureTitle: { fontWeight: 800, fontSize: 16, marginBottom: 6 } as React.CSSProperties,
  featureDesc: { color: "#777", fontSize: 14, lineHeight: 1.5 } as React.CSSProperties,
  formWrap: { maxWidth: 700, margin: "0 auto", padding: "48px 40px" } as React.CSSProperties,
  pageTitle: { fontSize: 32, fontWeight: 900, letterSpacing: -1, marginBottom: 6 } as React.CSSProperties,
  pageSubtitle: { color: "#666", marginBottom: 40, fontSize: 15 } as React.CSSProperties,
  card: { background: "#12121c", border: "1px solid #1e1e2e", borderRadius: 20, padding: 32 } as React.CSSProperties,
  fieldRow: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 } as React.CSSProperties,
  fieldGroup: { display: "flex", flexDirection: "column", gap: 6 } as React.CSSProperties,
  label: { fontSize: 13, fontWeight: 700, color: "#aaa", textTransform: "uppercase", letterSpacing: 0.5 } as React.CSSProperties,
  input: { background: "#0d0d18", border: "1px solid #2a2a3a", borderRadius: 10, padding: "12px 16px", color: "#f0f0f5", fontFamily: "inherit", fontSize: 15, outline: "none" } as React.CSSProperties,
  inputErr: { border: "1px solid #ef4444" } as React.CSSProperties,
  errMsg: { color: "#ef4444", fontSize: 12, marginTop: 2 } as React.CSSProperties,
  select: { background: "#0d0d18", border: "1px solid #2a2a3a", borderRadius: 10, padding: "12px 16px", color: "#f0f0f5", fontFamily: "inherit", fontSize: 15, outline: "none" } as React.CSSProperties,
  submitBtn: { width: "100%", background: "#f97316", color: "#fff", border: "none", borderRadius: 14, padding: "16px", fontSize: 17, fontWeight: 800, cursor: "pointer", marginTop: 24, fontFamily: "inherit" } as React.CSSProperties,
  successBox: { background: "#0d2818", border: "1px solid #10b981", borderRadius: 16, padding: 28, textAlign: "center", marginBottom: 32 } as React.CSSProperties,
  adminWrap: { maxWidth: 1200, margin: "0 auto", padding: "40px 32px" } as React.CSSProperties,
  statsRow: { display: "grid", gridTemplateColumns: "repeat(4,1fr)", gap: 16, marginBottom: 32 } as React.CSSProperties,
  statCard: (color: string): React.CSSProperties => ({ background: "#12121c", border: `1px solid ${color}22`, borderRadius: 16, padding: "22px 24px", borderLeft: `4px solid ${color}` }),
  statNum: { fontSize: 36, fontWeight: 900, marginBottom: 4 } as React.CSSProperties,
  statLabel: { color: "#666", fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.5 } as React.CSSProperties,
  toolbar: { display: "flex", gap: 12, marginBottom: 20, flexWrap: "wrap" as const },
  searchInput: { flex: 1, minWidth: 200, background: "#12121c", border: "1px solid #2a2a3a", borderRadius: 10, padding: "10px 16px", color: "#f0f0f5", fontFamily: "inherit", fontSize: 14, outline: "none" } as React.CSSProperties,
  filterBtn: (active: boolean): React.CSSProperties => ({ background: active ? "#f97316" : "#12121c", color: active ? "#fff" : "#888", border: "1px solid #2a2a3a", borderRadius: 8, padding: "8px 14px", cursor: "pointer", fontFamily: "inherit", fontWeight: 600, fontSize: 13 }),
  table: { width: "100%", borderCollapse: "collapse" as const },
  th: { textAlign: "left" as const, padding: "12px 16px", fontSize: 12, color: "#555", fontWeight: 700, textTransform: "uppercase" as const, letterSpacing: 0.5, borderBottom: "1px solid #1e1e2e" },
  td: { padding: "14px 16px", borderBottom: "1px solid #1a1a28", fontSize: 14, verticalAlign: "middle" as const },
  actionBtn: (color: string): React.CSSProperties => ({ background: `${color}22`, color: color, border: `1px solid ${color}44`, borderRadius: 6, padding: "4px 10px", cursor: "pointer", fontFamily: "inherit", fontSize: 12, fontWeight: 700 }),
  modal: { position: "fixed", inset: 0, background: "#000a", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 200, padding: 20 } as React.CSSProperties,
  modalCard: { background: "#12121c", border: "1px solid #2a2a3a", borderRadius: 20, padding: 32, maxWidth: 520, width: "100%", maxHeight: "85vh", overflowY: "auto" as const },
  loginWrap: { maxWidth: 400, margin: "80px auto", padding: "0 24px" } as React.CSSProperties,
  loginCard: { background: "#12121c", border: "1px solid #2a2a3a", borderRadius: 20, padding: 40 } as React.CSSProperties,
};
